version: "3.9"
services:
  app:
    build: .
    container_name: linkservice
    env_file: ./configs/database_connection.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - 50051:50051
    depends_on:
      - postgres

  postgres:
    build: ./database
    container_name: postgres
    env_file: ./configs/database_connection.env